{% set name = "aimz" %}
{% set version = "0.6.0" %}
{% set python_min = 3.11 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/aimz-{{ version }}.tar.gz
  sha256: 2fd086b7e867b812e977f01d22d718775e3c76712de6e9ca79ca75b6b54ed681

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - dask-core >=2025.5
    - jax >=0.7
    - numpyro >=0.19.0
    - scikit-learn >=1.6.1
    - xarray >=2025.4
    - zarr >=3,<4

test:
  imports:
    - aimz
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/aimz/
  summary: Scalable probabilistic impact modeling
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - markean
