{% set name = "aimz" %}
{% set version = "0.15.1" %}
{% set python_min = 3.11 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/aimz-{{ version }}.tar.gz
  sha256: 8b4abc86ff1592d6a1ba8fe39c3badb730049a7d8295635a365690037b4e2ff5

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - dask-core >=2026.1
    - jax >=0.10
    - numpyro >=0.21
    - psutil >=7
    - xarray >=2026.1
    - zarr >=3,<4

test:
  imports:
    - aimz
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/aimz/
  summary: Scalable probabilistic impact modeling
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - markean
